export const GET_TEXTS_FETCH = 'GET_TEXTS_FETCH';
export const GET_TEXTS_SUCCESS = 'GET_TEXTS_SUCCESS';
export const GET_TEXTS_IS_LOADING = 'GET_TEXTS_IS_LOADING';
export const GET_TEXTS_ERROR = 'GET_TEXTS_ERROR';