export const GET_TEXTS_FETCH = 'GET_TEXTS_FETCH';
export const GET_TEXTS_SUCCESS = 'GET_TEXTS_SUCCESS';
export const GET_TEXTS_IS_LOADING = 'GET_TEXTS_IS_LOADING';
export const GET_TEXTS_ERROR = 'GET_TEXTS_ERROR';

export const GET_TEXT_ITEM_FETCH = 'GET_TEXT_ITEM_FETCH';
export const GET_TEXT_ITEM_SUCCESS = 'GET_TEXT_ITEM_SUCCESS';
export const GET_TEXT_ITEM_IS_LOADING = 'GET_TEXT_ITEM_IS_LOADING';
export const GET_TEXT_ITEM_ERROR = 'GET_TEXT_ITEM_ERROR';

export const UPLOAD_TEXT_FETCH = 'UPLOAD_TEXTS_FETCH';
export const UPLOAD_TEXT_SUCCESS = 'UPLOAD_TEXTS_SUCCESS';
export const UPLOAD_TEXT_IS_LOADING = 'UPLOAD_TEXTS_IS_LOADING';
export const UPLOAD_TEXT_ERROR = 'UPLOAD_TEXTS_ERROR';