export const GET_TEXTS_FETCH = 'GET_TEXTS_FETCH';
export const GET_TEXTS_SUCCESS = 'GET_TEXTS_SUCCESS';
export const GET_TEXTS_IS_LOADING = 'GET_TEXTS_IS_LOADING';
export const GET_TEXTS_ERROR = 'GET_TEXTS_ERROR';

export const SORT_BY_FILTER = 'SORT_BY_FILTER';
export const ALPHABET_FILTER = 'ALPHABET_FILTER';
export const SEARCH_FILTER = 'SEARCH_FILTER';

export const UPDATE_TEXT = 'UPDATE_TEXT';