export const texts = [
    {
        caption: 'Test header text number 1 (peace of text)',
        body: "let's go to type something interesting may be for fun",
        tags: 'text, test, numbers',
        language: 'latin',
        rate: 34,
        owner: 'QWU&fule73_k.;z',
        yourSpeed: 350,
        bestSpeed: 368,
        bestSpeedOwner: 'QWU&fule73_k.;z',
        uploadDate: '05.07.2019'
    },
    {
        caption: 'Здесь будет отрывок из пьесы может быть',
        body: "let's go to type something interesting may be for fun",
        tags: 'text, test, numbers',
        language: 'latin',
        rate: 34,
        owner: 'Muhhamad Ali He',
        yourSpeed: 350,
        bestSpeed: 368,
        bestSpeedOwner: 'Muha',
        uploadDate: '05.07.2019'
    },
    {
        caption: 'test text number 3',
        body: "let's go to type something interesting may be for fun",
        tags: 'text, test, numbers',
        language: 'latin',
        rate: 34,
        owner: 'you',
        yourSpeed: 350,
        bestSpeed: 368,
        bestSpeedOwner: 'Muhhamad Ali',
        uploadDate: '05.07.2019'
    },
    {
        caption: 'test text number 4',
        body: "let's go to type something interesting may be for fun",
        tags: 'text, test, numbers',
        language: 'latin',
        rate: 34,
        owner: 'you',
        yourSpeed: 350,
        bestSpeed: 368,
        bestSpeedOwner: 'Muhh',
        uploadDate: '05.07.2019'
    },
    {
        caption: 'test text number 5',
        body: "let's go to type something interesting may be for fun",
        tags: 'text, test, numbers',
        language: 'latin',
        rate: 34,
        owner: 'you',
        yourSpeed: 350,
        bestSpeed: 368,
        bestSpeedOwner: 'Muhhamad Ali',
        uploadDate: '05.07.2019'
    },
    {
        caption: 'test text number 6',
        body: "let's go to type something interesting may be for fun",
        tags: 'text, test, numbers',
        language: 'latin',
        rate: 34,
        owner: 'you',
        yourSpeed: 350,
        bestSpeed: 368,
        bestSpeedOwner: 'Muhhamad Ali Henrens',
        uploadDate: '05.07.2019'
    },
    {
        caption: 'test text number 7',
        body: "let's go to type something interesting may be for fun",
        tags: 'text, test, numbers',
        language: 'latin',
        rate: 34,
        owner: 'you',
        yourSpeed: 350,
        bestSpeed: 368,
        bestSpeedOwner: 'Muhhamad Ali',
        uploadDate: '05.07.2019'
    },
    {
        caption: 'test text number 8',
        body: "flex-basis This defines the default size of an element before the remaining space is distributed. It can be a length (e.g. 20%, 5rem, etc.) or a keyword. The auto keyword means look at my width or height property (which was temporarily done by the main-size keyword until deprecated). The content keyword means  - this keyword isn't well supported yet, so it's hard to test and harder to know what its brethren max-content, min-content, and fit-content do.",
        tags: 'text, test, numbers',
        language: 'latin',
        rate: 34,
        owner: 'you',
        yourSpeed: 350,
        bestSpeed: 368,
        bestSpeedOwner: 'Muhhamad Ali',
        uploadDate: '05.07.2019'
    },
    {
        caption: 'test text number 9',
        body: "This is the shorthand for flex-grow, flex-shrink and flex-basis combined. The second and third parameters (flex-shrink and flex-basis) are optional. Default is 0 1 auto.",
        tags: 'text, test, numbers',
        language: 'latin',
        rate: 34,
        owner: 'you',
        yourSpeed: 350,
        bestSpeed: 368,
        bestSpeedOwner: 'Muhhamad Ali',
        uploadDate: '05.07.2019'
    },
    {
        caption: 'test text number 10',
        body: "This is the shorthand for flex-grow, flex-shrink and flex-basis combined. The second and third parameters (flex-shrink and flex-basis) are optional. Default is 0 1 auto.",
        tags: 'text, test, numbers',
        language: 'latin',
        rate: 34,
        owner: 'you',
        yourSpeed: 350,
        bestSpeed: 368,
        bestSpeedOwner: 'Muhhamad Ali',
        uploadDate: '05.07.2019'
    },
]